#ifndef _HE_Trigger_H
#define _HE_Trigger_H

#include "gpaddon.h"

#define HETRIGGER_COUNT 32

#ifndef HETRIGGER_ENABLED
#define HETRIGGER_ENABLED 0
#endif

#ifndef HETRIGGER_MUX_CHANNELS
#define HETRIGGER_MUX_CHANNELS 8
#endif

#ifndef HETRIGGER_S0_PIN
#define HETRIGGER_S0_PIN -1
#endif
#ifndef HETRIGGER_S1_PIN
#define HETRIGGER_S1_PIN -1
#endif
#ifndef HETRIGGER_S2_PIN
#define HETRIGGER_S2_PIN -1
#endif
#ifndef HETRIGGER_S3_PIN
#define HETRIGGER_S3_PIN -1
#endif

#ifndef HETRIGGER_ADC0
#define HETRIGGER_ADC0 -1
#endif
#ifndef HETRIGGER_ADC1
#define HETRIGGER_ADC1 -1
#endif
#ifndef HETRIGGER_ADC2
#define HETRIGGER_ADC2 -1
#endif
#ifndef HETRIGGER_ADC3
#define HETRIGGER_ADC3 -1
#endif

#ifndef HETRIGGER_SMOOTHING_ENABLED
#define HETRIGGER_SMOOTHING_ENABLED 1
#endif

#ifndef HETRIGGER_SMOOTHING_FACTOR
#define HETRIGGER_SMOOTHING_FACTOR 5
#endif

#ifndef HETRIGGER_DEFAULT_IDLE
#define HETRIGGER_DEFAULT_IDLE 150
#endif

#ifndef HETRIGGER_DEFAULT_ACTIVE
#define HETRIGGER_DEFAULT_ACTIVE 2000
#endif

#ifndef HETRIGGER_DEFAULT_PRESSED
#define HETRIGGER_DEFAULT_PRESSED 3500
#endif

#ifndef HETRIGGER_DEFAULT_POLARITY
#define HETRIGGER_DEFAULT_POLARITY 0
#endif

#ifndef HETRIGGER_DEFAULT_RELEASE
#define HETRIGGER_DEFAULT_RELEASE 2000
#endif

#ifndef HETRIGGER_DEFAULT_NOISE
#define HETRIGGER_DEFAULT_NOISE 30
#endif

#ifndef HETRIGGER_DEFAULT_RAPID
#define HETRIGGER_DEFAULT_RAPID 0
#endif

// 32 possible HE triggers
#ifndef HETRIGGER_HE0_ACTION
#define HETRIGGER_HE0_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE0_ACTIVE
#define HETRIGGER_HE0_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE0_IDLE
#define HETRIGGER_HE0_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE0_PRESSED
#define HETRIGGER_HE0_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE0_POLARITY
#define HETRIGGER_HE0_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE0_RELEASE
#define HETRIGGER_HE0_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE0_NOISE
#define HETRIGGER_HE0_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE0_RAPID
#define HETRIGGER_HE0_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE1_ACTION
#define HETRIGGER_HE1_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE1_ACTIVE
#define HETRIGGER_HE1_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE1_IDLE
#define HETRIGGER_HE1_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE1_PRESSED
#define HETRIGGER_HE1_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE1_POLARITY
#define HETRIGGER_HE1_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE1_RELEASE
#define HETRIGGER_HE1_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE1_NOISE
#define HETRIGGER_HE1_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE1_RAPID
#define HETRIGGER_HE1_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE2_ACTION
#define HETRIGGER_HE2_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE2_ACTIVE
#define HETRIGGER_HE2_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE2_IDLE
#define HETRIGGER_HE2_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE2_PRESSED
#define HETRIGGER_HE2_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE2_POLARITY
#define HETRIGGER_HE2_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE2_RELEASE
#define HETRIGGER_HE2_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE2_NOISE
#define HETRIGGER_HE2_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE2_RAPID
#define HETRIGGER_HE2_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE3_ACTION
#define HETRIGGER_HE3_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE3_ACTIVE
#define HETRIGGER_HE3_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE3_IDLE
#define HETRIGGER_HE3_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE3_PRESSED
#define HETRIGGER_HE3_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE3_POLARITY
#define HETRIGGER_HE3_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE3_RELEASE
#define HETRIGGER_HE3_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE3_NOISE
#define HETRIGGER_HE3_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE3_RAPID
#define HETRIGGER_HE3_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE4_ACTION
#define HETRIGGER_HE4_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE4_ACTIVE
#define HETRIGGER_HE4_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE4_IDLE
#define HETRIGGER_HE4_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE4_PRESSED
#define HETRIGGER_HE4_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE4_POLARITY
#define HETRIGGER_HE4_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE4_RELEASE
#define HETRIGGER_HE4_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE4_NOISE
#define HETRIGGER_HE4_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE4_RAPID
#define HETRIGGER_HE4_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE5_ACTION
#define HETRIGGER_HE5_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE5_ACTIVE
#define HETRIGGER_HE5_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE5_IDLE
#define HETRIGGER_HE5_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE5_PRESSED
#define HETRIGGER_HE5_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE5_POLARITY
#define HETRIGGER_HE5_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE5_RELEASE
#define HETRIGGER_HE5_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE5_NOISE
#define HETRIGGER_HE5_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE5_RAPID
#define HETRIGGER_HE5_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE6_ACTION
#define HETRIGGER_HE6_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE6_ACTIVE
#define HETRIGGER_HE6_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE6_IDLE
#define HETRIGGER_HE6_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE6_PRESSED
#define HETRIGGER_HE6_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE6_POLARITY
#define HETRIGGER_HE6_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE6_RELEASE
#define HETRIGGER_HE6_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE6_NOISE
#define HETRIGGER_HE6_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE6_RAPID
#define HETRIGGER_HE6_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE7_ACTION
#define HETRIGGER_HE7_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE7_ACTIVE
#define HETRIGGER_HE7_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE7_IDLE
#define HETRIGGER_HE7_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE7_PRESSED
#define HETRIGGER_HE7_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE7_POLARITY
#define HETRIGGER_HE7_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE7_RELEASE
#define HETRIGGER_HE7_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE7_NOISE
#define HETRIGGER_HE7_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE7_RAPID
#define HETRIGGER_HE7_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE8_ACTION
#define HETRIGGER_HE8_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE8_ACTIVE
#define HETRIGGER_HE8_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE8_IDLE
#define HETRIGGER_HE8_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE8_PRESSED
#define HETRIGGER_HE8_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE8_POLARITY
#define HETRIGGER_HE8_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE8_RELEASE
#define HETRIGGER_HE8_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE8_NOISE
#define HETRIGGER_HE8_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE8_RAPID
#define HETRIGGER_HE8_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE9_ACTION
#define HETRIGGER_HE9_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE9_ACTIVE
#define HETRIGGER_HE9_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE9_IDLE
#define HETRIGGER_HE9_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE9_PRESSED
#define HETRIGGER_HE9_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE9_POLARITY
#define HETRIGGER_HE9_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE9_RELEASE
#define HETRIGGER_HE9_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE9_NOISE
#define HETRIGGER_HE9_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE9_RAPID
#define HETRIGGER_HE9_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE10_ACTION
#define HETRIGGER_HE10_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE10_ACTIVE
#define HETRIGGER_HE10_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE10_IDLE
#define HETRIGGER_HE10_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE10_PRESSED
#define HETRIGGER_HE10_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE10_POLARITY
#define HETRIGGER_HE10_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE10_RELEASE
#define HETRIGGER_HE10_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE10_NOISE
#define HETRIGGER_HE10_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE10_RAPID
#define HETRIGGER_HE10_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE11_ACTION
#define HETRIGGER_HE11_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE11_ACTIVE
#define HETRIGGER_HE11_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE11_IDLE
#define HETRIGGER_HE11_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE11_PRESSED
#define HETRIGGER_HE11_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE11_POLARITY
#define HETRIGGER_HE11_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE11_RELEASE
#define HETRIGGER_HE11_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE11_NOISE
#define HETRIGGER_HE11_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE11_RAPID
#define HETRIGGER_HE11_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE12_ACTION
#define HETRIGGER_HE12_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE12_ACTIVE
#define HETRIGGER_HE12_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE12_IDLE
#define HETRIGGER_HE12_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE12_PRESSED
#define HETRIGGER_HE12_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE12_POLARITY
#define HETRIGGER_HE12_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE12_RELEASE
#define HETRIGGER_HE12_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE12_NOISE
#define HETRIGGER_HE12_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE12_RAPID
#define HETRIGGER_HE12_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE13_ACTION
#define HETRIGGER_HE13_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE13_ACTIVE
#define HETRIGGER_HE13_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE13_IDLE
#define HETRIGGER_HE13_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE13_PRESSED
#define HETRIGGER_HE13_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE13_POLARITY
#define HETRIGGER_HE13_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE13_RELEASE
#define HETRIGGER_HE13_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE13_NOISE
#define HETRIGGER_HE13_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE13_RAPID
#define HETRIGGER_HE13_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE14_ACTION
#define HETRIGGER_HE14_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE14_ACTIVE
#define HETRIGGER_HE14_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE14_IDLE
#define HETRIGGER_HE14_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE14_PRESSED
#define HETRIGGER_HE14_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE14_POLARITY
#define HETRIGGER_HE14_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE14_RELEASE
#define HETRIGGER_HE14_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE14_NOISE
#define HETRIGGER_HE14_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE14_RAPID
#define HETRIGGER_HE14_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE15_ACTION
#define HETRIGGER_HE15_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE15_ACTIVE
#define HETRIGGER_HE15_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE15_IDLE
#define HETRIGGER_HE15_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE15_PRESSED
#define HETRIGGER_HE15_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE15_POLARITY
#define HETRIGGER_HE15_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE15_RELEASE
#define HETRIGGER_HE15_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE15_NOISE
#define HETRIGGER_HE15_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE15_RAPID
#define HETRIGGER_HE15_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE16_ACTION
#define HETRIGGER_HE16_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE16_ACTIVE
#define HETRIGGER_HE16_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE16_IDLE
#define HETRIGGER_HE16_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE16_PRESSED
#define HETRIGGER_HE16_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE16_POLARITY
#define HETRIGGER_HE16_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE16_RELEASE
#define HETRIGGER_HE16_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE16_NOISE
#define HETRIGGER_HE16_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE16_RAPID
#define HETRIGGER_HE16_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE17_ACTION
#define HETRIGGER_HE17_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE17_ACTIVE
#define HETRIGGER_HE17_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE17_IDLE
#define HETRIGGER_HE17_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE17_PRESSED
#define HETRIGGER_HE17_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE17_POLARITY
#define HETRIGGER_HE17_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE17_RELEASE
#define HETRIGGER_HE17_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE17_NOISE
#define HETRIGGER_HE17_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE17_RAPID
#define HETRIGGER_HE17_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE18_ACTION
#define HETRIGGER_HE18_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE18_ACTIVE
#define HETRIGGER_HE18_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE18_IDLE
#define HETRIGGER_HE18_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE18_PRESSED
#define HETRIGGER_HE18_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE18_POLARITY
#define HETRIGGER_HE18_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE18_RELEASE
#define HETRIGGER_HE18_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE18_NOISE
#define HETRIGGER_HE18_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE18_RAPID
#define HETRIGGER_HE18_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE19_ACTION
#define HETRIGGER_HE19_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE19_ACTIVE
#define HETRIGGER_HE19_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE19_IDLE
#define HETRIGGER_HE19_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE19_PRESSED
#define HETRIGGER_HE19_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE19_POLARITY
#define HETRIGGER_HE19_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE19_RELEASE
#define HETRIGGER_HE19_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE19_NOISE
#define HETRIGGER_HE19_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE19_RAPID
#define HETRIGGER_HE19_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE20_ACTION
#define HETRIGGER_HE20_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE20_ACTIVE
#define HETRIGGER_HE20_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE20_IDLE
#define HETRIGGER_HE20_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE20_PRESSED
#define HETRIGGER_HE20_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE20_POLARITY
#define HETRIGGER_HE20_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE20_RELEASE
#define HETRIGGER_HE20_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE20_NOISE
#define HETRIGGER_HE20_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE20_RAPID
#define HETRIGGER_HE20_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE21_ACTION
#define HETRIGGER_HE21_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE21_ACTIVE
#define HETRIGGER_HE21_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE21_IDLE
#define HETRIGGER_HE21_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE21_PRESSED
#define HETRIGGER_HE21_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE21_POLARITY
#define HETRIGGER_HE21_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE21_RELEASE
#define HETRIGGER_HE21_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE21_NOISE
#define HETRIGGER_HE21_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE21_RAPID
#define HETRIGGER_HE21_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE22_ACTION
#define HETRIGGER_HE22_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE22_ACTIVE
#define HETRIGGER_HE22_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE22_IDLE
#define HETRIGGER_HE22_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE22_PRESSED
#define HETRIGGER_HE22_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE22_POLARITY
#define HETRIGGER_HE22_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE22_RELEASE
#define HETRIGGER_HE22_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE22_NOISE
#define HETRIGGER_HE22_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE22_RAPID
#define HETRIGGER_HE22_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE23_ACTION
#define HETRIGGER_HE23_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE23_ACTIVE
#define HETRIGGER_HE23_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE23_IDLE
#define HETRIGGER_HE23_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE23_PRESSED
#define HETRIGGER_HE23_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE23_POLARITY
#define HETRIGGER_HE23_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE23_RELEASE
#define HETRIGGER_HE23_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE23_NOISE
#define HETRIGGER_HE23_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE23_RAPID
#define HETRIGGER_HE23_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE24_ACTION
#define HETRIGGER_HE24_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE24_ACTIVE
#define HETRIGGER_HE24_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE24_IDLE
#define HETRIGGER_HE24_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE24_PRESSED
#define HETRIGGER_HE24_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE24_POLARITY
#define HETRIGGER_HE24_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE24_RELEASE
#define HETRIGGER_HE24_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE24_NOISE
#define HETRIGGER_HE24_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE24_RAPID
#define HETRIGGER_HE24_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE25_ACTION
#define HETRIGGER_HE25_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE25_ACTIVE
#define HETRIGGER_HE25_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE25_IDLE
#define HETRIGGER_HE25_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE25_PRESSED
#define HETRIGGER_HE25_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE25_POLARITY
#define HETRIGGER_HE25_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE25_RELEASE
#define HETRIGGER_HE25_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE25_NOISE
#define HETRIGGER_HE25_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE25_RAPID
#define HETRIGGER_HE25_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE26_ACTION
#define HETRIGGER_HE26_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE26_ACTIVE
#define HETRIGGER_HE26_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE26_IDLE
#define HETRIGGER_HE26_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE26_PRESSED
#define HETRIGGER_HE26_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE26_POLARITY
#define HETRIGGER_HE26_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE26_RELEASE
#define HETRIGGER_HE26_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE26_NOISE
#define HETRIGGER_HE26_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE26_RAPID
#define HETRIGGER_HE26_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE27_ACTION
#define HETRIGGER_HE27_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE27_ACTIVE
#define HETRIGGER_HE27_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE27_IDLE
#define HETRIGGER_HE27_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE27_PRESSED
#define HETRIGGER_HE27_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE27_POLARITY
#define HETRIGGER_HE27_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE27_RELEASE
#define HETRIGGER_HE27_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE27_NOISE
#define HETRIGGER_HE27_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE27_RAPID
#define HETRIGGER_HE27_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE28_ACTION
#define HETRIGGER_HE28_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE28_ACTIVE
#define HETRIGGER_HE28_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE28_IDLE
#define HETRIGGER_HE28_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE28_PRESSED
#define HETRIGGER_HE28_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE28_POLARITY
#define HETRIGGER_HE28_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE28_RELEASE
#define HETRIGGER_HE28_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE28_NOISE
#define HETRIGGER_HE28_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE28_RAPID
#define HETRIGGER_HE28_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE29_ACTION
#define HETRIGGER_HE29_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE29_ACTIVE
#define HETRIGGER_HE29_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE29_IDLE
#define HETRIGGER_HE29_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE29_PRESSED
#define HETRIGGER_HE29_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE29_POLARITY
#define HETRIGGER_HE29_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE29_RELEASE
#define HETRIGGER_HE29_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE29_NOISE
#define HETRIGGER_HE29_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE29_RAPID
#define HETRIGGER_HE29_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE30_ACTION
#define HETRIGGER_HE30_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE30_ACTIVE
#define HETRIGGER_HE30_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE30_IDLE
#define HETRIGGER_HE30_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE30_PRESSED
#define HETRIGGER_HE30_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE30_POLARITY
#define HETRIGGER_HE30_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE30_RELEASE
#define HETRIGGER_HE30_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE30_NOISE
#define HETRIGGER_HE30_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE30_RAPID
#define HETRIGGER_HE30_RAPID HETRIGGER_DEFAULT_RAPID
#endif
#ifndef HETRIGGER_HE31_ACTION
#define HETRIGGER_HE31_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE31_ACTIVE
#define HETRIGGER_HE31_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE31_IDLE
#define HETRIGGER_HE31_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE31_PRESSED
#define HETRIGGER_HE31_PRESSED HETRIGGER_DEFAULT_PRESSED
#endif
#ifndef HETRIGGER_HE31_POLARITY
#define HETRIGGER_HE31_POLARITY HETRIGGER_DEFAULT_POLARITY
#endif
#ifndef HETRIGGER_HE31_RELEASE
#define HETRIGGER_HE31_RELEASE HETRIGGER_DEFAULT_RELEASE
#endif
#ifndef HETRIGGER_HE31_NOISE
#define HETRIGGER_HE31_NOISE HETRIGGER_DEFAULT_NOISE
#endif
#ifndef HETRIGGER_HE31_RAPID
#define HETRIGGER_HE31_RAPID HETRIGGER_DEFAULT_RAPID
#endif

// HETrigger Module Name
#define HETriggerAddonName "Hall Effect Trigger"

class HETriggerAddon : public GPAddon {
public:
    virtual bool available();
    virtual void setup();
    virtual void process() {}
    virtual void preprocess();
    virtual void postprocess(bool sent) {}
    virtual void reinit() {}
    virtual std::string name() { return HETriggerAddonName; }
private:
    void selectChannel(uint8_t channel);
    uint16_t emaSmoothing(uint16_t value, uint16_t previous);
    int muxTotal;
    int selectPins;
    Pin_t muxPinArray[4];
    Pin_t selectPinArray[4];
    Pin_t lastADCSelected;

    uint16_t emaSmoothingReads[32];
    bool triggerActive[32];
    uint16_t lastIncrement[32];
    float emaSmoothingFactor;

    // Used during processing
    uint32_t mux;
    uint32_t channel;
    uint16_t value;
    uint16_t activationThreshold;
    uint16_t releaseThreshold;
};

#endif  // _HE_Trigger_H