#ifndef _HE_Trigger_H
#define _HE_Trigger_H

#include "gpaddon.h"

#define HETRIGGER_COUNT 32

#ifndef HETRIGGER_ENABLED
#define HETRIGGER_ENABLED 0
#endif

#ifndef HETRIGGER_MUX_CHANNELS
#define HETRIGGER_MUX_CHANNELS 8
#endif

#ifndef HETRIGGER_S0_PIN
#define HETRIGGER_S0_PIN -1
#endif
#ifndef HETRIGGER_S1_PIN
#define HETRIGGER_S1_PIN -1
#endif
#ifndef HETRIGGER_S2_PIN
#define HETRIGGER_S2_PIN -1
#endif
#ifndef HETRIGGER_S3_PIN
#define HETRIGGER_S3_PIN -1
#endif

#ifndef HETRIGGER_ADC0
#define HETRIGGER_ADC0 -1
#endif
#ifndef HETRIGGER_ADC1
#define HETRIGGER_ADC1 -1
#endif
#ifndef HETRIGGER_ADC2
#define HETRIGGER_ADC2 -1
#endif
#ifndef HETRIGGER_ADC3
#define HETRIGGER_ADC3 -1
#endif

#ifndef HETRIGGER_SMOOTHING_ENABLED
#define HETRIGGER_SMOOTHING_ENABLED 1
#endif

#ifndef HETRIGGER_SMOOTHING_FACTOR
#define HETRIGGER_SMOOTHING_FACTOR 5
#endif

#ifndef HETRIGGER_DEFAULT_IDLE
#define HETRIGGER_DEFAULT_IDLE 150
#endif

#ifndef HETRIGGER_DEFAULT_ACTIVE
#define HETRIGGER_DEFAULT_ACTIVE 2000
#endif

#ifndef HETRIGGER_DEFAULT_MAX
#define HETRIGGER_DEFAULT_MAX 3500
#endif

#ifndef HETRIGGER_DEFAULT_POLARITY
#define HETRIGGER_DEFAULT_POLARITY 0
#endif

// 32 possible HE triggers
#ifndef HETRIGGER_HE0_ACTION
#define HETRIGGER_HE0_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE0_ACTIVE
#define HETRIGGER_HE0_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE0_IDLE
#define HETRIGGER_HE0_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE0_MAX
#define HETRIGGER_HE0_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE0_POLARITY
#define HETRIGGER_HE0_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE1_ACTION
#define HETRIGGER_HE1_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE1_ACTIVE
#define HETRIGGER_HE1_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE1_IDLE
#define HETRIGGER_HE1_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE1_MAX
#define HETRIGGER_HE1_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE1_POLARITY
#define HETRIGGER_HE1_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE2_ACTION
#define HETRIGGER_HE2_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE2_ACTIVE
#define HETRIGGER_HE2_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE2_IDLE
#define HETRIGGER_HE2_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE2_MAX
#define HETRIGGER_HE2_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE2_POLARITY
#define HETRIGGER_HE2_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE3_ACTION
#define HETRIGGER_HE3_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE3_ACTIVE
#define HETRIGGER_HE3_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE3_IDLE
#define HETRIGGER_HE3_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE3_MAX
#define HETRIGGER_HE3_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE3_POLARITY
#define HETRIGGER_HE3_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE4_ACTION
#define HETRIGGER_HE4_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE4_ACTIVE
#define HETRIGGER_HE4_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE4_IDLE
#define HETRIGGER_HE4_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE4_MAX
#define HETRIGGER_HE4_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE4_POLARITY
#define HETRIGGER_HE4_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE5_ACTION
#define HETRIGGER_HE5_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE5_ACTIVE
#define HETRIGGER_HE5_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE5_IDLE
#define HETRIGGER_HE5_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE5_MAX
#define HETRIGGER_HE5_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE5_POLARITY
#define HETRIGGER_HE5_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE6_ACTION
#define HETRIGGER_HE6_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE6_ACTIVE
#define HETRIGGER_HE6_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE6_IDLE
#define HETRIGGER_HE6_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE6_MAX
#define HETRIGGER_HE6_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE6_POLARITY
#define HETRIGGER_HE6_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE7_ACTION
#define HETRIGGER_HE7_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE7_ACTIVE
#define HETRIGGER_HE7_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE7_IDLE
#define HETRIGGER_HE7_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE7_MAX
#define HETRIGGER_HE7_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE7_POLARITY
#define HETRIGGER_HE7_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE8_ACTION
#define HETRIGGER_HE8_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE8_ACTIVE
#define HETRIGGER_HE8_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE8_IDLE
#define HETRIGGER_HE8_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE8_MAX
#define HETRIGGER_HE8_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE8_POLARITY
#define HETRIGGER_HE8_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE9_ACTION
#define HETRIGGER_HE9_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE9_ACTIVE
#define HETRIGGER_HE9_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE9_IDLE
#define HETRIGGER_HE9_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE9_MAX
#define HETRIGGER_HE9_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE9_POLARITY
#define HETRIGGER_HE9_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE10_ACTION
#define HETRIGGER_HE10_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE10_ACTIVE
#define HETRIGGER_HE10_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE10_IDLE
#define HETRIGGER_HE10_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE10_MAX
#define HETRIGGER_HE10_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE10_POLARITY
#define HETRIGGER_HE10_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE11_ACTION
#define HETRIGGER_HE11_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE11_ACTIVE
#define HETRIGGER_HE11_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE11_IDLE
#define HETRIGGER_HE11_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE11_MAX
#define HETRIGGER_HE11_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE11_POLARITY
#define HETRIGGER_HE11_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE12_ACTION
#define HETRIGGER_HE12_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE12_ACTIVE
#define HETRIGGER_HE12_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE12_IDLE
#define HETRIGGER_HE12_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE12_MAX
#define HETRIGGER_HE12_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE12_POLARITY
#define HETRIGGER_HE12_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE13_ACTION
#define HETRIGGER_HE13_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE13_ACTIVE
#define HETRIGGER_HE13_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE13_IDLE
#define HETRIGGER_HE13_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE13_MAX
#define HETRIGGER_HE13_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE13_POLARITY
#define HETRIGGER_HE13_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE14_ACTION
#define HETRIGGER_HE14_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE14_ACTIVE
#define HETRIGGER_HE14_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE14_IDLE
#define HETRIGGER_HE14_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE14_MAX
#define HETRIGGER_HE14_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE14_POLARITY
#define HETRIGGER_HE14_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE15_ACTION
#define HETRIGGER_HE15_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE15_ACTIVE
#define HETRIGGER_HE15_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE15_IDLE
#define HETRIGGER_HE15_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE15_MAX
#define HETRIGGER_HE15_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE15_POLARITY
#define HETRIGGER_HE15_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE16_ACTION
#define HETRIGGER_HE16_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE16_ACTIVE
#define HETRIGGER_HE16_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE16_IDLE
#define HETRIGGER_HE16_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE16_MAX
#define HETRIGGER_HE16_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE16_POLARITY
#define HETRIGGER_HE16_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE17_ACTION
#define HETRIGGER_HE17_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE17_ACTIVE
#define HETRIGGER_HE17_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE17_IDLE
#define HETRIGGER_HE17_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE17_MAX
#define HETRIGGER_HE17_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE17_POLARITY
#define HETRIGGER_HE17_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE18_ACTION
#define HETRIGGER_HE18_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE18_ACTIVE
#define HETRIGGER_HE18_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE18_IDLE
#define HETRIGGER_HE18_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE18_MAX
#define HETRIGGER_HE18_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE18_POLARITY
#define HETRIGGER_HE18_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE19_ACTION
#define HETRIGGER_HE19_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE19_ACTIVE
#define HETRIGGER_HE19_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE19_IDLE
#define HETRIGGER_HE19_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE19_MAX
#define HETRIGGER_HE19_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE19_POLARITY
#define HETRIGGER_HE19_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE20_ACTION
#define HETRIGGER_HE20_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE20_ACTIVE
#define HETRIGGER_HE20_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE20_IDLE
#define HETRIGGER_HE20_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE20_MAX
#define HETRIGGER_HE20_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE20_POLARITY
#define HETRIGGER_HE20_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE21_ACTION
#define HETRIGGER_HE21_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE21_ACTIVE
#define HETRIGGER_HE21_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE21_IDLE
#define HETRIGGER_HE21_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE21_MAX
#define HETRIGGER_HE21_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE21_POLARITY
#define HETRIGGER_HE21_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE22_ACTION
#define HETRIGGER_HE22_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE22_ACTIVE
#define HETRIGGER_HE22_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE22_IDLE
#define HETRIGGER_HE22_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE22_MAX
#define HETRIGGER_HE22_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE22_POLARITY
#define HETRIGGER_HE22_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE23_ACTION
#define HETRIGGER_HE23_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE23_ACTIVE
#define HETRIGGER_HE23_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE23_IDLE
#define HETRIGGER_HE23_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE23_MAX
#define HETRIGGER_HE23_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE23_POLARITY
#define HETRIGGER_HE23_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE24_ACTION
#define HETRIGGER_HE24_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE24_ACTIVE
#define HETRIGGER_HE24_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE24_IDLE
#define HETRIGGER_HE24_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE24_MAX
#define HETRIGGER_HE24_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE24_POLARITY
#define HETRIGGER_HE24_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE25_ACTION
#define HETRIGGER_HE25_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE25_ACTIVE
#define HETRIGGER_HE25_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE25_IDLE
#define HETRIGGER_HE25_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE25_MAX
#define HETRIGGER_HE25_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE25_POLARITY
#define HETRIGGER_HE25_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE26_ACTION
#define HETRIGGER_HE26_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE26_ACTIVE
#define HETRIGGER_HE26_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE26_IDLE
#define HETRIGGER_HE26_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE26_MAX
#define HETRIGGER_HE26_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE26_POLARITY
#define HETRIGGER_HE26_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE27_ACTION
#define HETRIGGER_HE27_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE27_ACTIVE
#define HETRIGGER_HE27_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE27_IDLE
#define HETRIGGER_HE27_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE27_MAX
#define HETRIGGER_HE27_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE27_POLARITY
#define HETRIGGER_HE27_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE28_ACTION
#define HETRIGGER_HE28_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE28_ACTIVE
#define HETRIGGER_HE28_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE28_IDLE
#define HETRIGGER_HE28_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE28_MAX
#define HETRIGGER_HE28_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE28_POLARITY
#define HETRIGGER_HE28_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE29_ACTION
#define HETRIGGER_HE29_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE29_ACTIVE
#define HETRIGGER_HE29_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE29_IDLE
#define HETRIGGER_HE29_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE29_MAX
#define HETRIGGER_HE29_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE29_POLARITY
#define HETRIGGER_HE29_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE30_ACTION
#define HETRIGGER_HE30_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE30_ACTIVE
#define HETRIGGER_HE30_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE30_IDLE
#define HETRIGGER_HE30_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE30_MAX
#define HETRIGGER_HE30_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE30_POLARITY
#define HETRIGGER_HE30_POLARITY HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE31_ACTION
#define HETRIGGER_HE31_ACTION GpioAction::NONE
#endif
#ifndef HETRIGGER_HE31_ACTIVE
#define HETRIGGER_HE31_ACTIVE HETRIGGER_DEFAULT_ACTIVE
#endif
#ifndef HETRIGGER_HE31_IDLE
#define HETRIGGER_HE31_IDLE HETRIGGER_DEFAULT_IDLE
#endif
#ifndef HETRIGGER_HE31_MAX
#define HETRIGGER_HE31_MAX HETRIGGER_DEFAULT_MAX
#endif
#ifndef HETRIGGER_HE31_POLARITY
#define HETRIGGER_HE31_POLARITY HETRIGGER_DEFAULT_MAX
#endif

// HETrigger Module Name
#define HETriggerAddonName "Hall Effect Trigger"

class HETriggerAddon : public GPAddon {
public:
    virtual bool available();
    virtual void setup();
    virtual void process() {}
    virtual void preprocess();
    virtual void postprocess(bool sent) {}
    virtual void reinit() {}
    virtual std::string name() { return HETriggerAddonName; }
private:
    void selectChannel(uint8_t channel);
    uint16_t emaSmoothing(uint16_t value, uint16_t previous);
    int muxTotal;
    int selectPins;
    Pin_t muxPinArray[4];
    Pin_t selectPinArray[4];
    Pin_t lastADCSelected;

    uint16_t emaSmoothingReads[32];
    float emaSmoothingFactor;

    // Used during processing
    uint32_t mux;
    uint32_t channel;
    uint16_t value;
};

#endif  // _HE_Trigger_H