env:
  node: true
  browser: true
  es2021: true
parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:i18next/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    version: "18.2"
plugins:
  - react-refresh
  - i18next
rules:
  react-refresh/only-export-components: warn
  react/prop-types: off
  react/react-in-jsx-scope: off
  no-template-curly-in-string: off
  no-unused-vars: off
  react-hooks/exhaustive-deps: off
  no-extra-boolean-cast: off
