env:
  browser: true
  es2021: true
extends:
  - react-app
  # - eslint:recommended
  # - plugin:react/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  no-template-curly-in-string: off
  no-unused-vars: off
  react-hooks/exhaustive-deps: off
