#ifndef _PINVIEWERSCREEN_H_
#define _PINVIEWERSCREEN_H_

#include <map>
#include "GPGFX_UI_widgets.h"

class PinViewerScreen : public GPScreen {
    public:
        PinViewerScreen() {}
        PinViewerScreen(GPGFX* renderer) { setRenderer(renderer); }
        virtual ~PinViewerScreen(){}
        virtual int8_t update();
        virtual void init();
        virtual void shutdown();
    protected:
        virtual void drawScreen();
        uint16_t prevButtonState = 0;

        std::map<GpioAction,const char*> buttonLookup = {
            {GpioAction::BUTTON_PRESS_UP, CHAR_UP},
            {GpioAction::BUTTON_PRESS_DOWN, CHAR_DOWN},
            {GpioAction::BUTTON_PRESS_LEFT, CHAR_LEFT},
            {GpioAction::BUTTON_PRESS_RIGHT, CHAR_RIGHT},
            {GpioAction::BUTTON_PRESS_B1, "B1"},
            {GpioAction::BUTTON_PRESS_B2, "B2"},
            {GpioAction::BUTTON_PRESS_B3, "B3"},
            {GpioAction::BUTTON_PRESS_B4, "B4"},
            {GpioAction::BUTTON_PRESS_L1, "L1"},
            {GpioAction::BUTTON_PRESS_R1, "R1"},
            {GpioAction::BUTTON_PRESS_L2, "L2"},
            {GpioAction::BUTTON_PRESS_R2, "R2"},
            {GpioAction::BUTTON_PRESS_S1, "S1"},
            {GpioAction::BUTTON_PRESS_S2, "S2"},
            {GpioAction::BUTTON_PRESS_A1, "A1"},
            {GpioAction::BUTTON_PRESS_A2, "A2"},
            {GpioAction::BUTTON_PRESS_L3, "L3"},
            {GpioAction::BUTTON_PRESS_R3, "R3"},
            {GpioAction::BUTTON_PRESS_FN, "FN"},
            {GpioAction::BUTTON_PRESS_DDI_UP, "DDI" CHAR_UP},
            {GpioAction::BUTTON_PRESS_DDI_DOWN, "DDI" CHAR_DOWN},
            {GpioAction::BUTTON_PRESS_DDI_LEFT, "DDI" CHAR_LEFT},
            {GpioAction::BUTTON_PRESS_DDI_RIGHT, "DDI" CHAR_RIGHT},
            {GpioAction::SUSTAIN_DP_MODE_DP, "DP"},
            {GpioAction::SUSTAIN_DP_MODE_LS, "LS"},
            {GpioAction::SUSTAIN_DP_MODE_RS, "RS"},
            {GpioAction::SUSTAIN_SOCD_MODE_UP_PRIO, "SOCD-UP"},
            {GpioAction::SUSTAIN_SOCD_MODE_NEUTRAL, "SOCD-N"},
            {GpioAction::SUSTAIN_SOCD_MODE_SECOND_WIN, "SOCD-2W"},
            {GpioAction::SUSTAIN_SOCD_MODE_FIRST_WIN, "SOCD-1W"},
            {GpioAction::SUSTAIN_SOCD_MODE_BYPASS, "SOCD-BP"},
            {GpioAction::SUSTAIN_PROFILE_SLIDER_POSITION_1, "PROF1"},
            {GpioAction::SUSTAIN_PROFILE_SLIDER_POSITION_2, "PROF2"},
            {GpioAction::SUSTAIN_PROFILE_SLIDER_POSITION_3, "PROF3"},
            {GpioAction::SUSTAIN_PROFILE_SLIDER_POSITION_4, "PROF4"},
            {GpioAction::SUSTAIN_PROFILE_SLIDER_POSITION_5, "PROF5"},
            {GpioAction::SUSTAIN_PROFILE_SLIDER_POSITION_6, "PROF6"},
            {GpioAction::SUSTAIN_PROFILE_SLIDER_POSITION_7, "PROF7"},
            {GpioAction::SUSTAIN_PROFILE_SLIDER_POSITION_8, "PROF8"},
            {GpioAction::BUTTON_PRESS_TURBO, "TRB"},
            {GpioAction::BUTTON_PRESS_MACRO, "M"},
            {GpioAction::BUTTON_PRESS_MACRO_1, "M1"},
            {GpioAction::BUTTON_PRESS_MACRO_2, "M2"},
            {GpioAction::BUTTON_PRESS_MACRO_3, "M3"},
            {GpioAction::BUTTON_PRESS_MACRO_4, "M4"},
            {GpioAction::BUTTON_PRESS_MACRO_5, "M5"},
            {GpioAction::BUTTON_PRESS_MACRO_6, "M6"},
            {GpioAction::BUTTON_PRESS_A3, "A3"},
            {GpioAction::BUTTON_PRESS_A4, "A4"},
            {GpioAction::BUTTON_PRESS_E1, "E1"},
            {GpioAction::BUTTON_PRESS_E2, "E2"},
            {GpioAction::BUTTON_PRESS_E3, "E3"},
            {GpioAction::BUTTON_PRESS_E4, "E4"},
            {GpioAction::BUTTON_PRESS_E5, "E5"},
            {GpioAction::BUTTON_PRESS_E6, "E6"},
            {GpioAction::BUTTON_PRESS_E7, "E7"},
            {GpioAction::BUTTON_PRESS_E8, "E8"},
            {GpioAction::BUTTON_PRESS_E9, "E9"},
            {GpioAction::BUTTON_PRESS_E10, "E10"},
            {GpioAction::BUTTON_PRESS_E11, "E11"},
            {GpioAction::BUTTON_PRESS_E12, "E12"},
            {GpioAction::DIGITAL_DIRECTION_UP, "DIG-DIR" CHAR_UP},
            {GpioAction::DIGITAL_DIRECTION_DOWN, "DIG-DIR" CHAR_DOWN},
            {GpioAction::DIGITAL_DIRECTION_LEFT, "DIG-DIR" CHAR_LEFT},
            {GpioAction::DIGITAL_DIRECTION_RIGHT, "DIG-DIR" CHAR_RIGHT},
            {GpioAction::ANALOG_DIRECTION_LS_X_NEG, "LSX-"},
            {GpioAction::ANALOG_DIRECTION_LS_X_POS, "LSX+"},
            {GpioAction::ANALOG_DIRECTION_LS_Y_NEG, "LSY-"},
            {GpioAction::ANALOG_DIRECTION_LS_Y_POS, "LSY+"},
            {GpioAction::ANALOG_DIRECTION_RS_X_NEG, "RSX-"},
            {GpioAction::ANALOG_DIRECTION_RS_X_POS, "RSX+"},
            {GpioAction::ANALOG_DIRECTION_RS_Y_NEG, "RSY-"},
            {GpioAction::ANALOG_DIRECTION_RS_Y_POS, "RSY+"},
            {GpioAction::ANALOG_DIRECTION_MOD_LOW, "TILT-HI"},
            {GpioAction::ANALOG_DIRECTION_MOD_HIGH, "TILT-LO"},
            {GpioAction::BUTTON_PRESS_INPUT_REVERSE, "REV"},
            {GpioAction::SUSTAIN_FOCUS_MODE, "FOCUS"},
            {GpioAction::SUSTAIN_4_8_WAY_MODE, "4/8WAY"},
            {GpioAction::MENU_NAVIGATION_UP, "MENU" CHAR_UP},
            {GpioAction::MENU_NAVIGATION_DOWN, "MENU" CHAR_DOWN},
            {GpioAction::MENU_NAVIGATION_LEFT, "MENU" CHAR_LEFT},
            {GpioAction::MENU_NAVIGATION_RIGHT, "MENU" CHAR_RIGHT},
            {GpioAction::MENU_NAVIGATION_SELECT, "MENU-SEL"},
            {GpioAction::MENU_NAVIGATION_BACK, "MENU-BK"},
            {GpioAction::MENU_NAVIGATION_TOGGLE, "MENU-TGL"},
            {GpioAction::MODE_GUITAR_FRET_GREEN, "FRET-G"},
            {GpioAction::MODE_GUITAR_FRET_RED, "FRET-R"},
            {GpioAction::MODE_GUITAR_FRET_YELLOW, "FRET-Y"},
            {GpioAction::MODE_GUITAR_FRET_BLUE, "FRET-B"},
            {GpioAction::MODE_GUITAR_FRET_ORANGE, "FRET-O"},
            {GpioAction::MODE_GUITAR_FRET_SOLO_GREEN, "SOLO-G"},
            {GpioAction::MODE_GUITAR_FRET_SOLO_RED, "SOLO-R"},
            {GpioAction::MODE_GUITAR_FRET_SOLO_YELLOW, "SOLO-Y"},
            {GpioAction::MODE_GUITAR_FRET_SOLO_BLUE, "SOLO-B"},
            {GpioAction::MODE_GUITAR_FRET_SOLO_ORANGE, "SOLO-O"},
            {GpioAction::MODE_GUITAR_WHAMMY, "WHAMMY!"},
            {GpioAction::MODE_GUITAR_PICKUP, "PICKUP"},
            {GpioAction::MODE_GUITAR_TILT, "TILT"},
            {GpioAction::MODE_DRUM_RED_DRUMPAD, "DRUM-R"},
            {GpioAction::MODE_DRUM_BLUE_DRUMPAD, "DRUM-B"},
            {GpioAction::MODE_DRUM_YELLOW_DRUMPAD, "DRUM-Y"},
            {GpioAction::MODE_DRUM_GREEN_DRUMPAD, "DRUM-G"},
            {GpioAction::MODE_DRUM_YELLOW_CYMBAL, "CYM-Y"},
            {GpioAction::MODE_DRUM_BLUE_CYMBAL, "CYM-B"},
            {GpioAction::MODE_DRUM_GREEN_CYMBAL, "CYM-G"},
            {GpioAction::MODE_DRUM_KICK_PEDAL_LEFT, "KICK-L"},
            {GpioAction::MODE_DRUM_KICK_PEDAL_RIGHT, "KICK-R"},
            {GpioAction::MODE_HOTAS_RUDDER_LEFT, "RUD-L"},
            {GpioAction::MODE_HOTAS_RUDDER_RIGHT, "RUD-R"},
            {GpioAction::MODE_HOTAS_THROTTLE_FORWARD, "THR-F"},
            {GpioAction::MODE_HOTAS_THROTTLE_REVERSE, "THR-R"},
            {GpioAction::MODE_HOTAS_ROCKER_LEFT, "ROCK-L"},
            {GpioAction::MODE_HOTAS_ROCKER_RIGHT, "ROCK-R"},
            {GpioAction::MODE_HOTAS_PEDAL_LEFT, "PED-L"},
            {GpioAction::MODE_HOTAS_PEDAL_RIGHT, "PED-R"},
            {GpioAction::MODE_HOTAS_PEDAL_RUDDER_LEFT, "PRUD-L"},
            {GpioAction::MODE_HOTAS_PEDAL_RUDDER_RIGHT, "PRUD-R"},
            {GpioAction::MODE_WHEEL_STEERING_LEFT, "STEER-L"},
            {GpioAction::MODE_WHEEL_STEERING_RIGHT, "STEER-R"},
            {GpioAction::MODE_WHEEL_SHIFTER_GEAR_1, "GEAR-1"},
            {GpioAction::MODE_WHEEL_SHIFTER_GEAR_2, "GEAR-2"},
            {GpioAction::MODE_WHEEL_SHIFTER_GEAR_3, "GEAR-3"},
            {GpioAction::MODE_WHEEL_SHIFTER_GEAR_4, "GEAR-4"},
            {GpioAction::MODE_WHEEL_SHIFTER_GEAR_5, "GEAR-5"},
            {GpioAction::MODE_WHEEL_SHIFTER_GEAR_6, "GEAR-6"},
            {GpioAction::MODE_WHEEL_SHIFTER_GEAR_R, "GEAR-R"},
            {GpioAction::MODE_WHEEL_SHIFTER_GEAR_N, "GEAR-N"},
            {GpioAction::MODE_WHEEL_SHIFTER_GEAR_UP, "SHIFT+"},
            {GpioAction::MODE_WHEEL_SHIFTER_GEAR_DOWN, "SHIFT-"},
            {GpioAction::MODE_WHEEL_BUTTON_PLUS, "WHEEL+"},
            {GpioAction::MODE_WHEEL_BUTTON_MINUS, "WHEEL-"},
            {GpioAction::MODE_WHEEL_DIAL_UP, "DIAL+"},
            {GpioAction::MODE_WHEEL_DIAL_DOWN, "DIAL-"},
            {GpioAction::MODE_WHEEL_DIAL_ENTER, "DIAL-ENT"},
            {GpioAction::MODE_WHEEL_PEDAL_GAS, "GAS"},
            {GpioAction::MODE_WHEEL_PEDAL_BRAKE, "BRAKE"},
            {GpioAction::MODE_WHEEL_PEDAL_CLUTCH, "CLUTCH"},
        };
};

#endif