name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Build steps
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm install --frozen-lockfile
        working-directory: site
      - name: Build
        run: npm run build
        working-directory: site

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: site/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
